import { Model } from "./model";
import { type AssetReader } from "./asset-reader";
export declare class PmxLoader {
    private view;
    private offset;
    private decoder;
    private encoding;
    private additionalVec4Count;
    private vertexIndexSize;
    private textureIndexSize;
    private materialIndexSize;
    private boneIndexSize;
    private morphIndexSize;
    private rigidBodyIndexSize;
    private textures;
    private materials;
    private bones;
    private inverseBindMatrices;
    private joints0;
    private weights0;
    private morphs;
    private vertexCount;
    private rigidbodies;
    private joints;
    private constructor();
    static load(url: string): Promise<Model>;
    static loadFromBuffer(buffer: ArrayBuffer): Model;
    static loadFromReader(reader: AssetReader, pmxLogicalPath: string): Promise<Model>;
    private parse;
    private parseHeader;
    private parseVertices;
    private parseIndices;
    private parseTextures;
    private parseMaterials;
    private parseBones;
    private parseMorphs;
    private skipDisplayFrames;
    private parseRigidbodies;
    private parseJoints;
    private computeInverseBind;
    private toModel;
    private getUint8;
    private getUint16;
    private getVertexIndex;
    private getNonVertexIndex;
    private getInt32;
    private getFloat32;
    private getString;
    private getText;
    private getIndex;
}
//# sourceMappingURL=pmx-loader.d.ts.map